[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#1683ff"
backgroundColor = "#06101d"
secondaryBackgroundColor = "#0a1930"
textColor = "#eef6ff"
font = "sans serif"
